name: pypi deployer
on:
  push:
    branches:
      - 'docker'

jobs:
  # Build and deploy manylinux wheel
  Linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy manylinux wheels
        uses: ./

  # deploy source distribution
  Source-dist:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: create source distribution
        run: python setup.py sdist
      - name: upload source distribution
        run: |
          pip install twine
          twine upload dist/*
        continue-on-error: true

  Mac-build:
    runs-on: ${{ matrix.os }}
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      FC: gfortran-9
      DYLD_FALLBACK_LIBRARY_PATH: /usr/local/lib
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Symlink fortran
        run: ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
      - name: Install homebrew deps
        run: brew install fftw netcdf lapack
      - name: Build specfab
        run: |
          make lib
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build wheel
        run: |
          pip install wheel
          pip wheel --no-deps -w ~/dist/ .
      - name: Delocate Wheel
        run: |
            pip install delocate
            delocate-wheel -w ~/fixed_wheels -v ~/dist/*.whl
      - name: upload wheel
        run: |
          pip install twine
          twine upload ~/fixed_wheels/*
        continue-on-error: true
