name: pypi deployer
on:
  push:
    branches:
      - 'docker'

jobs:
  # Build and deploy manylinux wheel
  Linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy manylinux wheels
        uses: ./

  # deploy source distribution
  Source-dist:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: create source distribution
        run: python setup.py sdist
      - name: upload source distribution
        run: |
          pip install twine
          twine upload dist/*
        continue-on-error: true
